import { Varela_Round  } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";


const outfit = Varela_Round ({
  weight: ['400'],
  subsets: ["latin"],
});


export const metadata = {
  title: "Ace Expense",
  description: "Generated by create next app",
  icons:{
    icon:['/favicon.ico?v=4']
  }
  
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" className="dark">

      <body className={outfit.className}>

        {children}</body>
    </html>
    </ClerkProvider>
  );
}